import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "success-light": "#3B6939",
        "success-light-on": "#FFFFFF",
        "success-light-container": "#BCF0B4",
        "success-light-on-container": "#002204",
        "success-dark": "#A1D39A",
        "warning-light": "#775A0B",
        "warning-light-on": "#FFFFFF",
        "warning-light-container": "#FFDF9E",
        "warning-light-on-container": "#261A00",
        "warning-dark": "#E9C16C",
        "info-light": "#36618E",
        "info-light-on": "#FFFFFF",
        "info-light-container": "#D1E4FF",
        "info-light-on-container": "#001D36",
        "info-dark": "#A0CAFD",
        "attention-light": "#685F12",
        "attention-light-on": "#FFFFFF",
        "attention-light-container": "#F1E48A",
        "attention-light-on-container": "#201C00",
        "attention-dark": "#D4C871",
        "error-light": "#B3261E",
        "error-light-on": "#FFFFFF",
        "error-light-container": "#FFDAD6",
        "error-light-on-container": "#410002",
        "error-dark": "#FFB4AB",
        light: {
          primary: "#00696C",
          surfaceTint: "#00696C",
          onPrimary: "#FFFFFF",
          primaryContainer: "#9CF1F3",
          onPrimaryContainer: "#004F51",
          secondary: "#4A6364",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#CCE8E8",
          onSecondaryContainer: "#324B4C",
          tertiary: "#4D5F7C",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#D5E3FF",
          onTertiaryContainer: "#354863",
          error: "#BA1A1A",
          onError: "#FFFFFF",
          errorContainer: "#FFDAD6",
          onErrorContainer: "#93000A",
          background: "#F4FBFA",
          onBackground: "#161D1D",
          surface: "#F4FBFA",
          onSurface: "#161D1D",
          surfaceVariant: "#DAE4E4",
          onSurfaceVariant: "#3F4949",
          outline: "#6F7979",
          outlineVariant: "#BEC8C8",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#2B3232",
          inverseOnSurface: "#ECF2F2",
          inversePrimary: "#80D4D7",
          primaryFixed: "#9CF1F3",
          onPrimaryFixed: "#002021",
          primaryFixedDim: "#80D4D7",
          onPrimaryFixedVariant: "#004F51",
          secondaryFixed: "#CCE8E8",
          onSecondaryFixed: "#041F20",
          secondaryFixedDim: "#B0CCCC",
          onSecondaryFixedVariant: "#324B4C",
          tertiaryFixed: "#D5E3FF",
          onTertiaryFixed: "#061C36",
          tertiaryFixedDim: "#B4C7E9",
          onTertiaryFixedVariant: "#354863",
          surfaceDim: "#D5DBDB",
          surfaceBright: "#F4FBFA",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#EFF5F4",
          surfaceContainer: "#E9EFEF",
          surfaceContainerHigh: "#E3E9E9",
          surfaceContainerHighest: "#DDE4E3",
        },
        "light-medium-contrast": {
          primary: "#003D3F",
          surfaceTint: "#00696C",
          onPrimary: "#FFFFFF",
          primaryContainer: "#16797C",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#213A3B",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#587272",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#243752",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#5B6E8C",
          onTertiaryContainer: "#FFFFFF",
          error: "#740006",
          onError: "#FFFFFF",
          errorContainer: "#CF2C27",
          onErrorContainer: "#FFFFFF",
          background: "#F4FBFA",
          onBackground: "#161D1D",
          surface: "#F4FBFA",
          onSurface: "#0C1212",
          surfaceVariant: "#DAE4E4",
          onSurfaceVariant: "#2E3838",
          outline: "#4A5454",
          outlineVariant: "#656F6F",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#2B3232",
          inverseOnSurface: "#ECF2F2",
          inversePrimary: "#80D4D7",
          primaryFixed: "#16797C",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#005F61",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#587272",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#40595A",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#5B6E8C",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#435672",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#C1C8C7",
          surfaceBright: "#F4FBFA",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#EFF5F4",
          surfaceContainer: "#E3E9E9",
          surfaceContainerHigh: "#D8DEDE",
          surfaceContainerHighest: "#CCD3D2",
        },
        "light-high-contrast": {
          primary: "#003233",
          surfaceTint: "#00696C",
          onPrimary: "#FFFFFF",
          primaryContainer: "#005254",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#173031",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#344D4E",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#192D47",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#374A66",
          onTertiaryContainer: "#FFFFFF",
          error: "#600004",
          onError: "#FFFFFF",
          errorContainer: "#98000A",
          onErrorContainer: "#FFFFFF",
          background: "#F4FBFA",
          onBackground: "#161D1D",
          surface: "#F4FBFA",
          onSurface: "#000000",
          surfaceVariant: "#DAE4E4",
          onSurfaceVariant: "#000000",
          outline: "#242E2E",
          outlineVariant: "#414B4B",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#2B3232",
          inverseOnSurface: "#FFFFFF",
          inversePrimary: "#80D4D7",
          primaryFixed: "#005254",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#00393B",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#344D4E",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#1E3738",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#374A66",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#20334E",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#B4BABA",
          surfaceBright: "#F4FBFA",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#ECF2F2",
          surfaceContainer: "#DDE4E3",
          surfaceContainerHigh: "#CFD6D5",
          surfaceContainerHighest: "#C1C8C7",
        },
      },
      fontSize: {
        "display-large": ["57px", { lineHeight: "64px" }],
        "display-medium": ["45px", { lineHeight: "52px" }],
        "display-small": ["36px", { lineHeight: "44px" }],

        "headline-large": ["32px", { lineHeight: "40px" }],
        "headline-medium": ["28px", { lineHeight: "36px" }],
        "headline-small": ["24px", { lineHeight: "32px" }],

        "title-large": ["22px", { lineHeight: "28px" }],
        "title-medium": ["16px", { lineHeight: "24px" }],
        "title-small": ["14px", { lineHeight: "20px" }],

        "body-large": ["16px", { lineHeight: "24px" }],
        "body-medium": ["14px", { lineHeight: "20px" }],
        "body-small": ["12px", { lineHeight: "16px" }],

        "label-large": ["14px", { lineHeight: "20px" }],
        "label-medium": ["12px", { lineHeight: "16px" }],
        "label-small": ["11px", { lineHeight: "16px" }],
      },
      screens: {
        custom: "898px",
        custom2: "1429px",
        custom3: "1287px",
        lgg: "1400px",
        cc: "822px",
        ccc: "1096px",
        cccc: "900px",
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("@tailwindcss/typography")],
} satisfies Config;
